### ISSUE TITLE
Permission denied /var/lib/docker/containers

### ISSUE THREAD

**Issue by chanyshev** [bitnami/bitnami-docker-fluentd-exporter#2]
### Name and Version

bitnami/fluentd:1.14.6

### What steps will reproduce the bug?

docker-compose.yml
```
version: '3.3'

services:

  fluentd:
    image: bitnami/fluentd:latest
    user: root
    container_name: fluentd
    volumes:
      - './fluentd.conf:/opt/bitnami/fluentd/conf/fluentd.conf'
      - './data:/opt/bitnami/fluentd/logs'
      - '/var/lib/docker/containers:/var/lib/docker/containers:ro'
    ports:
      - '9122:9122'
    networks:
      - fluentd

networks:
  fluentd:
    driver: bridge
```
`docker-compose exec fluentd bash`
![image](https://user-images.githubusercontent.com/44210753/165688417-d71e9461-1159-4843-aaef-4533f45fe45e.png)

### What is the expected behavior?

My expectations, the running process from the root user

### What do you see instead?

I run the command for check permissions
su -s /bin/bash fluentd 
cd var/lib/docker/containers/4c951b535ecd99947292c400bafee666917c381a4e807347eb344a9a9c1d881e
and I get an error 'Permission denied"
